### ISSUE TITLE
Add `gfx_window_glutin` to Piston's ecosystem to fill a hole

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/eco#150]
`gfx_window_glutin` depends on `gfx`, but this is not noticed by the algorithm. When gfx bumps a version, the versions to `gfx_window_glutin` should also be bumped.

**Comment by alwayscodingsince111970** [comment]
I'd be happy to take this up. I might need some help with this though, I'm not quite sure where the change needs to be made.

**Comment by bvssvni** [comment]
It's added to Gfx ecosystem, so I think we should close this for now.
