### ISSUE TITLE
OpenSSL build problems on Windows

### ISSUE THREAD

**Issue by alwayscodingsince111970** [PistonDevelopers/eco#174]
I run into build problems with Windows on both the `msvc` and `gcc` toolchains. The problems are with the `openssl` and `openssl-sys-extras` crates.

Error with the `openssl` crate:
`src/c_helpers.c(1): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory`

Error with the `openssl-sys-extras` crate:
`src/openssl_shim.c(1): fatal error C1083: Cannot open include file: 'openssl/hmac.h': No such file or directory`

A possible solution to the problem may be to set up OpenSSL headers in Windows, and to have them visible in the PATH.

**Comment by bvssvni** [comment]
I changed to reqwest instead of hyper.

Reopen if this is still a problem.

Closing.
