### ISSUE TITLE
Why do we lock to specific versions?

### ISSUE THREAD

**Issue by xaviershay** [PistonDevelopers/eco#82]
_Not sure right place to ask this and here seems as good as any._

Looking at a selection of `Cargo.toml` files from across piston, they all appear to have declared specific versions of their dependencies. This is weird to me - I want to push out a new version of `sdl2_window` that adds the new joystick events (so depends on pistoncore-input 0.7), but seems like I'll have to update virtually every project that depends on input since they're tied to 0.6. It seems that using more flexible dependencies (`~> 0.7.0`) would make updates much easier.
1. Maybe this "just works" with rust and I'm being too paranoid?
2. Perhaps this is deliberate pre-1.0 to ensure everything is always on latest?
3. (not totally related) It's not obvious to me how to use `eco`'s output to sequence a release of the new `sdl2_window`. Do I have to do them _all_ in _order_? There are a lot...

**Comment by xaviershay** [comment]
... I'm also happy to not care about this issue and let you do releases :)

**Comment by bvssvni** [comment]
You have misunderstood how semver works in Cargo. `0.7.3` means `[0.7.3, 0.8.0)`. The first non-zero numbers indicates a breaking change. The other numbers is the minimum version. See https://github.com/PistonDevelopers/piston/wiki/crates.io-and-semver.
